core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("developers/", include("resumes.urls")),
    path("", include("pages.urls")),
    path("admin/", admin.site.urls),
]

pages/urls.py
from django.urls import path
from pages.views import index, about

app_name = "page"

urlpatterns = [
    path("", index, name="root"),
    path("about", about, name="about"),
]

resumes/urls.py
from django.urls import path
from . import views

app_name = "resume"

urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("<id>", views.show, name="show"),
    path("<id>/edit", views.edit, name="edit"),
    path("<id>/delete", views.delete, name="delete"),
]

resumes/models.py
from django.db import models


# Create your models here.
class Resume(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    introduce = models.CharField(max_length=200)
    profile = models.TextField()
    online = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} ({self.email})"

resumes/forms/resume_form.py
from django.forms import ModelForm
from resumes.models import Resume
from django.forms.widgets import TextInput, Textarea, CheckboxInput, EmailInput


class ResumeForm(ModelForm):
    class Meta:
        model = Resume
        fields = ["name", "email", "introduce", "profile", "online"]
        widgets = {
            "name": TextInput(attrs={"class": "input"}),
            "email": EmailInput(attrs={"class": "input"}),
            "introduce": TextInput(attrs={"class": "input"}),
            "profile": Textarea(attrs={"class": "textarea", "rows": 5}),
            "online": CheckboxInput(attrs={"class": "input"}),
        }

        labels = {
            "name": "姓名",
            "email": "Email",
            "introduce": "簡介",
            "profile": "個人檔案",
            "online": "是否上線",
        }

pages/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect


def index(req):
    return render(req, "pages/index.html")


def about(req):
    return render(req, "pages/about.html")

resumes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Resume
from django.http import HttpResponse
from .forms.resume_form import ResumeForm


# Create your views here.
def index(req):
    if req.method == "POST":
        form = ResumeForm(req.POST)

        if form.is_valid():
            form.save()
            return redirect("resume:index")
        else:
            return render(req, "resumes/new.html", {"form": form})

    items = Resume.objects.all()
    return render(req, "resumes/index.html", {"items": items})


def show(req, id):
    item = get_object_or_404(Resume, pk=id)
    form = ResumeForm(req.POST, instance=item)

    if req.method == "POST":
        form = ResumeForm(req.POST, instance=item)

        if form.is_valid():
            form.save()
            return redirect("resume:show", item.id)
        else:
            return render(req, "resumes/edit.html", {"form": form, "item": item})

    return render(req, "resumes/show.html", {"form": form, "item": item})


def new(req):
    form = ResumeForm()
    return render(req, "resumes/new.html", {"form": form})


def edit(req, id):
    item = get_object_or_404(Resume, pk=id)
    form = ResumeForm(instance=item)
    return render(req, "resumes/edit.html", {"form": form, "item": item})


def delete(req, id):
    item = get_object_or_404(Resume, pk=id)
    item.delete()
    return redirect("resume:index")

pages/templates/pages/about.html
{% extends "layout/base.html" %} {% block content %}
<h1>關於我們</h1>
{% endblock %}

pages/templates/pages/index.html
{% extends "layout/base.html" %} {% block content %}
<h1>首頁</h1>
{% endblock %}

resumes/templates/resumes/edit.html
{% extends "layout/base.html" %} 
{% block content %}
{% load static %}
<h1>編輯 resume</h1>

<form action="{% url 'resume:show' item.id %}" method="post">
  {% csrf_token %} 
  {% for field in form %}
  <div class="form-control">
    <label class="label">{{ field.label }}</label>
    {{ field }}
    <span class="text-red-500">{{ field.errors }}</span>
  </div>
  {% endfor %}

  <div>
    <button class="btn btn-primary">更新</button>
  </div>
</form>

{% endblock %}

resumes/templates/resumes/index.html
{% extends "layout/base.html" %} {% block content %}{% load static %}
<h1>Developers 列表</h1>
<a href="{% url 'resume:new' %}">新增</a>

<!-- <img src="{% static 'images/IMG_03.JPG' %}" width="300" /> -->
<ul>
  {% for item in items %}
  <li>
    {{ item.name }}
    <a href="{% url 'resume:show' item.id %}">{{ item.email }}</a>
    <a href="{% url 'resume:edit' item.id %}">編輯</a>
    <a href="{% url 'resume:delete' item.id %}">刪除</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

resumes/templates/resumes/new.html
{% extends "layout/base.html" %} 
{% block content %}
{% load static %}
<h1>新增 resume</h1>

<form action="{% url 'resume:index' %}" method="post">
  {% csrf_token %} 
  {% for field in form %}
  <div class="form-control">
    <label class="label">{{ field.label }}</label>
    {{ field }}
    <span class="text-red-500">{{ field.errors }}</span>
  </div>
  {% endfor %}

  <div>
    <button class="btn btn-primary">新增</button>
  </div>
</form>

{% endblock %}

resumes/templates/resumes/show.html
{% extends "layout/base.html" %} 
{% block content %}
{% load static %}
<h1>resume</h1>

  {% for field in form %}
  <div class="form-control">
    <label class="label">{{ field.label }}</label>
    {{ item.name }}
  </div>
  {% endfor %}

  <div>
    <a href="{% url 'resume:edit' item.id %}" class="btn btn-primary">編輯</a>
    <a href="{% url 'resume:delete' item.id %}" class="btn btn-primary">刪除</a>
  </div>

{% endblock %}

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
  </head>
  <body>
    {% include "layout/navbar.html" %}
    <main class="container mx-auto">{% block content %} {% endblock %}</main>
  </body>
</html>

templates/layout/navbar.html
<nav class="bg-blue-200 px-6 py-2">
  <ul class="flex gap-2">
    <li><a href="{% url 'page:root' %}">首頁</a></li>
    <li><a href="{% url 'page:about' %}">關於我們</a></li>
    <li><a href="{% url 'resume:index' %}">developers</a></li>
  </ul>
</nav>